const fs = require("fs");

const friktionSnapshot = JSON.parse(
  fs.readFileSync("./mainnet-tvl-snapshots/friktionSnapshot.json")
);

type JSONValue =
  | string
  | number
  | boolean
  | { [x: string]: JSONValue }
  | Array<JSONValue>;

const staticData: {
  globalIds: string[];
  staticInfoByGlobalId: Record<string, JSONValue>;
} = {
  // Sorted naturally based on our weight on them

  globalIds: Object.keys(friktionSnapshot.usdValueByGlobalId),
  staticInfoByGlobalId: {},
};

/*
Example of the friktionSnapshot variable:
friktionSnapshot = {
  allMainnetVolts: [
    {
      globalId: 'mainnet_income_call_btc',
      voltVaultId: 'CdZ1Mgo3927bsYdKK5rnzGtwek3NLWdvoTSSm2TJjdqW',
      extraVaultDataId: '6MpBDp3TCFTYrokZaGSpm5k5Wq9GT1P3SKx15eMvtNnh',
      vaultAuthority: 'DA1M8mw7GnPNKU9ReANtHPQyuVzKZtsuuSbCyc2uX2du',
      quoteMint: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
      underlyingMint: '9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E',
      depositTokenMint: '9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E',
      shareTokenMint: '3BjcHXvyzMsjmeqE2qFLx45K4XFx3JPiyRnjJiF5MAHt',
      shareTokenSymbol: 'fcBTC',
      shareTokenDecimals: 6,
      depositPool: 'A57Bn4Sj6o9H3U9wmU9GAvNdyTSS3P1pmkWRkAgNHXLK',
      premiumPool: '7ULgSWrAaKvK7iWawFVGW6km7hqAfG1Zpb1zsQemfPh6',
      spotSerumMarketId: '2NksTwSCzD2XERcZN5FHgTWhCVPePWt59mBKmsKGhbhP',
      depositTokenSymbol: 'BTC',
      depositTokenCoingeckoId: 'bitcoin',
      underlyingTokenSymbol: 'BTC',
      underlyingTokenCoingeckoId: 'bitcoin',
      voltType: 1,
      apy: 16.98,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: ''
    },
    {
      globalId: 'mainnet_income_call_sol',
      voltVaultId: 'CbPemKEEe7Y7YgBmYtFaZiECrVTP5sGrYzrrrviSewKY',
      extraVaultDataId: 'HDQFvghwrjCZjVcKiFZD3amopbW5WX97juPvKsV3WGv2',
      vaultAuthority: 'Hxtb6APfNtf9m8jJjh7uYp8fCTGr9aeHxBSfiPqCrV6G',
      quoteMint: 'EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v',
      underlyingMint: 'So11111111111111111111111111111111111111112',
      depositTokenMint: 'So11111111111111111111111111111111111111112',
      shareTokenMint: '4Hnh1UCC6HLzx9NaGKnTVHR2bANcRrhydumdHCnrT3i2',
      shareTokenSymbol: 'fcSOL',
      shareTokenDecimals: 9,
      depositPool: 'unrWTSSfz6H7DzYYHRTuTCK3yVzR1YUNqUn7xWwr4Z5',
      premiumPool: 'Dq3ZMPnpXqxqRmMaLKdGphsX7M1bxccaNuWHiqDkceSY',
      spotSerumMarketId: 'Aj3bg9mGwGyDAkxtWKhHVsJV8X2fhKsZ3tpN1NfYbjWd',
      depositTokenSymbol: 'SOL',
      depositTokenCoingeckoId: 'solana',
      underlyingTokenSymbol: 'SOL',
      underlyingTokenCoingeckoId: 'solana',
      voltType: 1,
      apy: 29.56,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: 'mainnet_income_call_sol_high'
    },
  ]
}
*/

const exampleStaticInfo: Record<string, "always"> = {
  globalId: "always",
  voltVaultId: "always",
  extraVaultDataId: "always",
  vaultAuthority: "always",
  quoteMint: "always",
  underlyingMint: "always",
  depositTokenMint: "always",
  shareTokenMint: "always",
  shareTokenSymbol: "always",
  shareTokenDecimals: "always",
  depositPool: "always",
  premiumPool: "always",
  spotSerumMarketId: "always",
  depositTokenSymbol: "always",
  depositTokenCoingeckoId: "always",
  underlyingTokenSymbol: "always",
  underlyingTokenCoingeckoId: "always",
  voltType: "always",

  // apy: 18.89, // NEVER!
  isVoltage: "always",
  isInCircuits: "always",
  highVoltage: "always",
};

// Loop through all the friktionSnapshot.allMainnetVolts and add them to the staticData.staticInfoByGlobalId. We also validate that all the keys in exampleStaticInfo are present.
for (const globalId of friktionSnapshot.allMainnetVolts) {
  const staticInfo: Record<string, JSONValue> = {};
  for (const key in exampleStaticInfo) {
    if (globalId[key] === undefined) {
      throw new Error(
        `Missing ${key} in friktionSnapshot.allMainnetVolts for ${globalId}`
      );
    }
    staticInfo[key] = globalId[key];
  }
  staticData.staticInfoByGlobalId[globalId.globalId] = staticInfo;
}

const frozenFriktionSnapshot: {
  globalIds: string[];
  staticInfoByGlobalId: Record<string, Record<string, JSONValue> | undefined>;
} = {
  globalIds: [
    "mainnet_income_call_sol",
    "mainnet_income_call_sol_high",
    "mainnet_income_call_btc",
    "mainnet_income_call_eth",
    "mainnet_income_call_marinade",
    "mainnet_income_call_avax",
    "mainnet_income_call_socean",
    "mainnet_income_call_ftt",
    "mainnet_income_call_srm",
    "mainnet_income_call_step",
    "mainnet_income_call_samo",
    "mainnet_income_call_near",
    "mainnet_income_call_sbr",
    "mainnet_income_call_mngo",
    "mainnet_income_call_ray",
    "mainnet_income_call_stsol",
    "mainnet_income_call_luna",
    "mainnet_income_put_sol",
    "mainnet_income_put_sol_high",
    "mainnet_income_put_btc",
    "mainnet_income_put_eth",
    "mainnet_income_put_pai",
    "mainnet_income_put_tsUSDC",
    "mainnet_income_call_btc_step_circuits",
    "mainnet_income_call_sol_step_circuits",
    "mainnet_income_put_sol_step_circuits",
    "mainnet_income_call_sol_parrot_circuits",
    "mainnet_income_put_sol_parrot_circuits",
    "mainnet_income_put_btc_step_circuits",
    "mainnet_income_put_sol_uxd_circuits",
    "mainnet_income_put_mngo",
    "mainnet_income_put_uxd",
    "mainnet_income_put_luna",
    "mainnet_income_perp_btc",
    "mainnet_basis_usdc_sol",
    "mainnet_basis_usdc_btc",
  ],
  staticInfoByGlobalId: {
    mainnet_income_call_btc: {
      globalId: "mainnet_income_call_btc",
      voltVaultId: "CdZ1Mgo3927bsYdKK5rnzGtwek3NLWdvoTSSm2TJjdqW",
      extraVaultDataId: "6MpBDp3TCFTYrokZaGSpm5k5Wq9GT1P3SKx15eMvtNnh",
      vaultAuthority: "DA1M8mw7GnPNKU9ReANtHPQyuVzKZtsuuSbCyc2uX2du",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E",
      depositTokenMint: "9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E",
      shareTokenMint: "3BjcHXvyzMsjmeqE2qFLx45K4XFx3JPiyRnjJiF5MAHt",
      shareTokenSymbol: "fcBTC",
      shareTokenDecimals: 6,
      depositPool: "A57Bn4Sj6o9H3U9wmU9GAvNdyTSS3P1pmkWRkAgNHXLK",
      premiumPool: "7ULgSWrAaKvK7iWawFVGW6km7hqAfG1Zpb1zsQemfPh6",
      spotSerumMarketId: "2NksTwSCzD2XERcZN5FHgTWhCVPePWt59mBKmsKGhbhP",
      depositTokenSymbol: "BTC",
      depositTokenCoingeckoId: "bitcoin",
      underlyingTokenSymbol: "BTC",
      underlyingTokenCoingeckoId: "bitcoin",
      voltType: 1,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_income_call_sol: {
      globalId: "mainnet_income_call_sol",
      voltVaultId: "CbPemKEEe7Y7YgBmYtFaZiECrVTP5sGrYzrrrviSewKY",
      extraVaultDataId: "HDQFvghwrjCZjVcKiFZD3amopbW5WX97juPvKsV3WGv2",
      vaultAuthority: "Hxtb6APfNtf9m8jJjh7uYp8fCTGr9aeHxBSfiPqCrV6G",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "So11111111111111111111111111111111111111112",
      depositTokenMint: "So11111111111111111111111111111111111111112",
      shareTokenMint: "4Hnh1UCC6HLzx9NaGKnTVHR2bANcRrhydumdHCnrT3i2",
      shareTokenSymbol: "fcSOL",
      shareTokenDecimals: 9,
      depositPool: "unrWTSSfz6H7DzYYHRTuTCK3yVzR1YUNqUn7xWwr4Z5",
      premiumPool: "Dq3ZMPnpXqxqRmMaLKdGphsX7M1bxccaNuWHiqDkceSY",
      spotSerumMarketId: "Aj3bg9mGwGyDAkxtWKhHVsJV8X2fhKsZ3tpN1NfYbjWd",
      depositTokenSymbol: "SOL",
      depositTokenCoingeckoId: "solana",
      underlyingTokenSymbol: "SOL",
      underlyingTokenCoingeckoId: "solana",
      voltType: 1,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "mainnet_income_call_sol_high",
    },
    mainnet_income_call_sol_high: {
      globalId: "mainnet_income_call_sol_high",
      voltVaultId: "6ESYJXX4tqSTZrTRQbHodQZEwU7jd4fKWvStBpttRB4c",
      extraVaultDataId: "9iuExpjrxkLda7FRhgfWAUZX4EFUaLnewGYZXaZYpow4",
      vaultAuthority: "wJAoeEG2sfQ1xgXUNVVkJ5mCTCw4SLc6oJafDwf6jTf",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "So11111111111111111111111111111111111111112",
      depositTokenMint: "So11111111111111111111111111111111111111112",
      shareTokenMint: "DNa849drqW19uBV5X9ohpJ5brRGzq856gk3HDRqveFrA",
      shareTokenSymbol: "fcSOLHigh",
      shareTokenDecimals: 9,
      depositPool: "9gQVba4aPF6nc2Tkv3BZmWrerJRmDSwxpTB6bfAiV97Q",
      premiumPool: "5cxywfaDUUc4xzGow1t15QQQhTwsWpkySzKYyAuxPGFY",
      spotSerumMarketId: "Aj3bg9mGwGyDAkxtWKhHVsJV8X2fhKsZ3tpN1NfYbjWd",
      depositTokenSymbol: "SOL",
      depositTokenCoingeckoId: "solana",
      underlyingTokenSymbol: "SOL",
      underlyingTokenCoingeckoId: "solana",
      voltType: 1,
      isVoltage: true,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_income_call_marinade: {
      globalId: "mainnet_income_call_marinade",
      voltVaultId: "9RcdLHX8rkfjo4ze2uyvhfQGjX6wAZtbvmBf3aK6wqrG",
      extraVaultDataId: "2SN4oJJp8B3bVuQHkrHzMGuo7ibdFPdU7SqdSK7SuTBA",
      vaultAuthority: "6asST5hurmxJ8uFvh7ZRWkrMfSEzjEAJ4DNR1is3G6eH",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So",
      depositTokenMint: "mSoLzYCxHdYgdzU16g5QSh3i5K3z3KZK7ytfqcJm7So",
      shareTokenMint: "6UA3yn28XecAHLTwoCtjfzy3WcyQj1x13bxnH8urUiKt",
      shareTokenSymbol: "fcmSOL",
      shareTokenDecimals: 9,
      depositPool: "CeR66gft7PRuaNxUVrekexGt6PQvsWFcLhrYFmzWzqPZ",
      premiumPool: "6mGFgUHBfaEXWSLn5b9udZbeFcq44nzu17eWnpCD21va",
      spotSerumMarketId: "9NxokJVFWiEXz5nrwfTDPoKXj46Nz6MxL1KLvxtGMT5m",
      depositTokenSymbol: "mSOL",
      depositTokenCoingeckoId: "msol",
      underlyingTokenSymbol: "mSOL",
      underlyingTokenCoingeckoId: "msol",
      voltType: 1,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_income_call_samo: {
      globalId: "mainnet_income_call_samo",
      voltVaultId: "CMVV4kfSdJRufiTNrrhr6PsvYY8SFhNs3TVjsWS3rJvP",
      extraVaultDataId: "2BU1z1e1h3adbsLYpnARMa4JCsZYMhrFC16jGPqb9ZYq",
      vaultAuthority: "7zev38J4jebnpACswV8iqjhDK9jsC1MGHtuAE2SPvqeZ",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU",
      depositTokenMint: "7xKXtg2CW87d97TXJSDpbD5jBkheTqA83TZRuJosgAsU",
      shareTokenMint: "9Wtfq4A7nGxQ6c89xhPBj4ipQyj1jeXntPBzDQknhHas",
      shareTokenSymbol: "fcSAMO",
      shareTokenDecimals: 9,
      depositPool: "CkKUQRsmNcXGLoazmet3VoYayTADF1r7T47XGbcD6Z6T",
      premiumPool: "5tqb8GJwJJK7ed5ab8Z5cxhLm2mjCYyw2M1S4UpE8CNs",
      spotSerumMarketId: "E6LmqE7JS7dbFFpsYFrNx27xsBLTZQKFbEJTzo363Un2",
      depositTokenSymbol: "SAMO",
      depositTokenCoingeckoId: "samoyedcoin",
      underlyingTokenSymbol: "SAMO",
      underlyingTokenCoingeckoId: "samoyedcoin",
      voltType: 1,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_income_call_near: {
      globalId: "mainnet_income_call_near",
      voltVaultId: "7P7oU1dTxXVU1Pked1DnEnr4GrrQb549zMAY4VmjChDo",
      extraVaultDataId: "37tASwXheKJTLPD6HHLniT5GsU8e4v755mVox5faAn83",
      vaultAuthority: "8XfzVjDJU2ZekawjA7fhUHQt2KNGVYv8qq1AzuGZ7iyK",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "BYPsjxa3YuZESQz1dKuBw1QSFCSpecsm8nCQhY5xbU1Z",
      depositTokenMint: "BYPsjxa3YuZESQz1dKuBw1QSFCSpecsm8nCQhY5xbU1Z",
      shareTokenMint: "9w6ntom9RfZLxX1uVdmjD6yHi8VJezJQYVWP9pMTHXfd",
      shareTokenSymbol: "fcNEAR",
      shareTokenDecimals: 9,
      depositPool: "As2arxFwrVQLX2wgZCW5zRkBEfmyeBVX7STzbetoWoyr",
      premiumPool: "Ckxvk8x6RK8xmFM2q28SbuqKgtAmayTgm77XAATVTusJ",
      spotSerumMarketId: "77UaXUjEJ9GeWw2WNabymtZy7ezKmwGfCG8C7edsW7xD",
      depositTokenSymbol: "NEAR",
      depositTokenCoingeckoId: "near",
      underlyingTokenSymbol: "NEAR",
      underlyingTokenCoingeckoId: "near",
      voltType: 1,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_income_call_eth: {
      globalId: "mainnet_income_call_eth",
      voltVaultId: "A2jbvwftkAzU5hLUmBePdfqZQsop7jydZirLS5NsRVtx",
      extraVaultDataId: "8fdEXEywMGXPx9T8iv8PGdd2KGX9ez3U1TTzapk8xhYR",
      vaultAuthority: "FThcy5XXvab5u3jbA6NjWKdMNiCSV3oY5AAkvEvpa8wp",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs",
      depositTokenMint: "7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs",
      shareTokenMint: "GjnoPUjQiEUYWuKAbMax2cM1Eony8Yutc133wuSun9hS",
      shareTokenSymbol: "fcETH",
      shareTokenDecimals: 6,
      depositPool: "6n9UCuP8HAvusfTWET5ck7fmyfSis7ND5BXzme59wJsE",
      premiumPool: "bQHPBzL8K9jtByXqpcUi4RXU7Nc4XuwLMXLosptAfJX",
      spotSerumMarketId: "DsWLLr4QQpXpMzQ8Y4p68Sj6Ei3fGGwA6c672dtyDhAA",
      depositTokenSymbol: "ETH",
      depositTokenCoingeckoId: "ethereum",
      underlyingTokenSymbol: "ETH",
      underlyingTokenCoingeckoId: "ethereum",
      voltType: 1,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_income_call_ftt: {
      globalId: "mainnet_income_call_ftt",
      voltVaultId: "8qjBanq5cxc3FzsaEznKfpsbPwfMVoB6AxLXY7pe3fEX",
      extraVaultDataId: "ATkNEzFX7ZygpzGMLRphSgfiK512nBBZHcKjjJdFgMdq",
      vaultAuthority: "7KqHFuUksvNhrWgoacKkqyp2RwfBNdypCYgK9nxD1d6K",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "EzfgjvkSwthhgHaceR3LnKXUoRkP6NUhfghdaHAj1tUv",
      depositTokenMint: "EzfgjvkSwthhgHaceR3LnKXUoRkP6NUhfghdaHAj1tUv",
      shareTokenMint: "7wDh4VCTPwx41kvbLE6fkFgMEjnqw7NpGJvQtNabCm2B",
      shareTokenSymbol: "fcFTT",
      shareTokenDecimals: 6,
      depositPool: "HcGvtMseBQTZVf9qrhkSW1zkiK8hUVnatybkeTfe3dJc",
      premiumPool: "FBJxvpWzzLbwHxjcgv2ZBGUYcHCcMDSnWzWAiLbGSkzH",
      spotSerumMarketId: "GWjUq2xcTVzaWbpJ3quTSeJnFbicWamcFZREyyNHCHJe",
      depositTokenSymbol: "FTT",
      depositTokenCoingeckoId: "ftx-token",
      underlyingTokenSymbol: "FTT",
      underlyingTokenCoingeckoId: "ftx-token",
      voltType: 1,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_income_call_srm: {
      globalId: "mainnet_income_call_srm",
      voltVaultId: "Ef2CD9yhQE7BvReQXct68uuYFW8GLKj62u2YPfmua3JY",
      extraVaultDataId: "9e7XC1K2sPbDALCA7ZD8oxockHLe6KtXjEKhjEzqEGuj",
      vaultAuthority: "2P427N5sYcEXvZAZwqNzjXEHsBMESQoLyjNquTSmGPMb",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt",
      depositTokenMint: "SRMuApVNdxXokk5GT7XD5cUUgXMBCoAz2LHeuAoKWRt",
      shareTokenMint: "5SLqZSywodLS8ih6U2AAioZrxpgR149hR8SApmCB7r5X",
      shareTokenSymbol: "fcSRM",
      shareTokenDecimals: 6,
      depositPool: "JBPXzHLMDTN3BLACACcBHM1CAfNz2r1s6tUMUhCMgGCZ",
      premiumPool: "A2sXsMsnAbtuk4RhxVc5ZbJq6s6SPVSLPWJzkHNrqGXm",
      spotSerumMarketId: "DaTyog7M78LnH69yowfVKRAnETPEeJPjyeh1BpKDuQeD",
      depositTokenSymbol: "SRM",
      depositTokenCoingeckoId: "serum",
      underlyingTokenSymbol: "SRM",
      underlyingTokenCoingeckoId: "serum",
      voltType: 1,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_income_call_mngo: {
      globalId: "mainnet_income_call_mngo",
      voltVaultId: "DxSADpEUR8xULRdWwb37pN8mjPHHC5D8aRnyUAvVSYHa",
      extraVaultDataId: "xwQiKPudYRonxSF6JUUfQHyhWXD2DUrME9cjiva6gd8",
      vaultAuthority: "B3yakZxwomkmnCxRr8ZmQtiWgtxtVBuCREDFDdAvcCVQ",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "MangoCzJ36AjZyKwVj3VnYU4GTonjfVEnJmvvWaxLac",
      depositTokenMint: "MangoCzJ36AjZyKwVj3VnYU4GTonjfVEnJmvvWaxLac",
      shareTokenMint: "4sTuzTYfcE2NF7zy6Sy8XhVcNLa6JQSLrx3roy97n4sD",
      shareTokenSymbol: "fcMNGO",
      shareTokenDecimals: 6,
      depositPool: "CE3Fen8teV2SRAJbS6REpdhVxatMXQgLy2PENUKBxYRL",
      premiumPool: "8RLCLT3JtXuRHeCMcyhXQsAycJyU9xnDt4L5dphVG27y",
      spotSerumMarketId: "3zb9bvQ5jeY9wFyr9MSeNqkFf5Ch3DTvY49Q6476E4HF",
      depositTokenSymbol: "MNGO",
      depositTokenCoingeckoId: "mango-markets",
      underlyingTokenSymbol: "MNGO",
      underlyingTokenCoingeckoId: "mango-markets",
      voltType: 1,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_income_call_socean: {
      globalId: "mainnet_income_call_socean",
      voltVaultId: "3ZYabzsHY2XGuVBBbAgrxitPhmHSKLDCKqEp3vpX9Jb1",
      extraVaultDataId: "5J3MHJAkHG3otVPhFAxgAcNV6cURk2CFyTLpHPKAbYeu",
      vaultAuthority: "A5MpyajTy6hdsg3S2em5ukcgY1ZBhxTxEKv8BgHajv1A",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "5oVNBeEEQvYi1cX3ir8Dx5n1P7pdxydbGF2X4TxVusJm",
      depositTokenMint: "5oVNBeEEQvYi1cX3ir8Dx5n1P7pdxydbGF2X4TxVusJm",
      shareTokenMint: "5VmdHqvRMbXivuC34w4Hux9zb1y9moiBEQmXDrTR1kV",
      shareTokenSymbol: "fcscnSOL",
      shareTokenDecimals: 9,
      depositPool: "7sp9EGacXqxNswsiS4hajmA7tXTjc8niBb7P1Gouq916",
      premiumPool: "wsGw7z4zH8CQRyBr5VspJPv7eYNTnnC6GgjeqRQeUEE",
      spotSerumMarketId: "4ge6UnhomusubG4S5bYGBYk2JFskvQ9axLf9FB1fGpLY",
      depositTokenSymbol: "scnSOL",
      depositTokenCoingeckoId: "socean-staked-sol",
      underlyingTokenSymbol: "scnSOL",
      underlyingTokenCoingeckoId: "socean-staked-sol",
      voltType: 1,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_income_call_sbr: {
      globalId: "mainnet_income_call_sbr",
      voltVaultId: "5b2VBmdZAmnFpmWD6hi5xWFeaf4equVwNp25q1UWC9FP",
      extraVaultDataId: "FyxL7QKDXqcNgtVZ9uAXEvaQbz5t6cRLTsj4krmUYo6C",
      vaultAuthority: "BH7Jg3f97FyeGxsPR7FFskvfqGiaLeUnJ9Ksda53Jj8h",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1",
      depositTokenMint: "Saber2gLauYim4Mvftnrasomsv6NvAuncvMEZwcLpD1",
      shareTokenMint: "DPMCwE9z9jXaDVDti5aKhdgCWGgsvioz6ZvB9eZjH7UE",
      shareTokenSymbol: "fcSBR",
      shareTokenDecimals: 6,
      depositPool: "FU2qxQeDVSrM4TYT2Z9s16oq8s5rbPSmrcyybLu1nApD",
      premiumPool: "BUDHLE9NSL1F9Vdq2dtbcHthnHEvHsLN9gUD8Jzuk3PA",
      spotSerumMarketId: "APRoymKQLaXf68LxzGAJTYR3VVe9nTXmDZKJWNfmabg2",
      depositTokenSymbol: "SBR",
      depositTokenCoingeckoId: "saber",
      underlyingTokenSymbol: "SBR",
      underlyingTokenCoingeckoId: "saber",
      voltType: 1,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_income_call_luna: {
      globalId: "mainnet_income_call_luna",
      voltVaultId: "4jx7Fec8kmwvabqTYp9M7C2zPfhivFgiqqzajn9Ns2ba",
      extraVaultDataId: "DH6aU2HP6f7hhiamxWWB6kF52gARbMhE11jT6WCANc6K",
      vaultAuthority: "5oV1Yf8q1oQgPYuHjepjmKFuaG2Wng9dzTqbSWhU5W2X",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "F6v4wfAdJB8D8p77bMXZgYt8TDKsYxLYxH5AFhUkYx9W",
      depositTokenMint: "F6v4wfAdJB8D8p77bMXZgYt8TDKsYxLYxH5AFhUkYx9W",
      shareTokenMint: "95sn4kgeJnnBfRCD8S2quu4HS9Y6vb7JDuXrarnmEjYE",
      shareTokenSymbol: "fcLUNA",
      shareTokenDecimals: 6,
      depositPool: "3nWapVJ5ocrGyM6r5rUJrAXbcRKa2w2v9rVbbqe74jk6",
      premiumPool: "GJkz2heU1AQCyGSXZAnKDGHYtY8xubBXDFvWZXzTXStt",
      spotSerumMarketId: "6oxqAenMejUcgcnY43L4PuBhKwjpMRESZyP2MpKQEedR",
      depositTokenSymbol: "LUNA",
      depositTokenCoingeckoId: "terra-luna",
      underlyingTokenSymbol: "LUNA",
      underlyingTokenCoingeckoId: "terra-luna",
      voltType: 1,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_income_call_ray: {
      globalId: "mainnet_income_call_ray",
      voltVaultId: "4LtxyBUH8PsRea21s7CaaYWtq7KutcZ4x8r6PTmUCcvs",
      extraVaultDataId: "EhH6Vw3DwvGNPKYDDVgZAjP63dBXw8Eg3EHb1ixz8WpX",
      vaultAuthority: "A6XsYxGj9wpqUZG81XwgQJ2zJ3efCbuWSQfnkHqUSmdM",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
      depositTokenMint: "4k3Dyjzvzp8eMZWUXbBCjEvwSkkk59S5iCNLY3QrkX6R",
      shareTokenMint: "SoAnGsHVqSyaN4MjWoPCcftC1V6oSeNxLJjF5TXrtuL",
      shareTokenSymbol: "fcRAY",
      shareTokenDecimals: 6,
      depositPool: "2dNuf4XfF1h2NsZW55XyYBLvtCvv9D3gRdyj6fNpFyFK",
      premiumPool: "HwKeBJg3PnngV1gRiBk78Fs3LU8dw1tcRiVPuG5vx9Pi",
      spotSerumMarketId: "9XUVkBf8K38iXJPos77wsMnJoniX7YNH17Rbzw1qmh9K",
      depositTokenSymbol: "RAY",
      depositTokenCoingeckoId: "raydium",
      underlyingTokenSymbol: "RAY",
      underlyingTokenCoingeckoId: "raydium",
      voltType: 1,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_income_call_step: {
      globalId: "mainnet_income_call_step",
      voltVaultId: "8YtJU58RUbvrdqCyTK7zJBSmCafVvZfysdXYq3W7YDai",
      extraVaultDataId: "6hSjQYdLAwVvBAnf9ye5XjbhDx8dky31BWr6jq34MAfu",
      vaultAuthority: "FiEHDTKT6X7VFwGaUmsm1XXYr8vvkoSR5EqcY4znpefq",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "StepAscQoEioFxxWGnh2sLBDFp9d8rvKz2Yp39iDpyT",
      depositTokenMint: "StepAscQoEioFxxWGnh2sLBDFp9d8rvKz2Yp39iDpyT",
      shareTokenMint: "AQFLXqLLofcbUCoi5HPfuuvX6vMPafubZfBNBMumnKq2",
      shareTokenSymbol: "fcSTEP",
      shareTokenDecimals: 9,
      depositPool: "6RYwy311TyRiMHvZ4oRRKb2H8bCKEfUj1SV3UPmYWRX9",
      premiumPool: "5YBLM2Lw2iRn4ysrbxJNgNKkStmBoPNdkeKLChpWmFJC",
      spotSerumMarketId: "Di8cexymBtunKZb8CQC9g6188k98NeZEhoscED9oExWM",
      depositTokenSymbol: "STEP",
      depositTokenCoingeckoId: "step-finance",
      underlyingTokenSymbol: "STEP",
      underlyingTokenCoingeckoId: "step-finance",
      voltType: 1,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_income_call_stsol: {
      globalId: "mainnet_income_call_stsol",
      voltVaultId: "9q5kEMkY28NXjxovpr1ssLLCAHgmyYzNmgAksp6voeJ8",
      extraVaultDataId: "H5kRu6xZ2yZw86VuyfvkVbRq2Ac4LTM2arWLG3QKtC1o",
      vaultAuthority: "2Ahpeqc1bo7Y4dVknvZUVfZPhHhym7JN6az2XMbUA6QA",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "7dHbWXmci3dT8UFYWYZweBLXgycu7Y3iL6trKn1Y7ARj",
      depositTokenMint: "7dHbWXmci3dT8UFYWYZweBLXgycu7Y3iL6trKn1Y7ARj",
      shareTokenMint: "EPoDdEcDQ478YNRAiMYMHLs7mEnmo5z9322Q2D5exKFU",
      shareTokenSymbol: "fcstSOL",
      shareTokenDecimals: 9,
      depositPool: "4aoSKSt2jdqg3R6x9gJxFSVXnR7XLnjYBbhxW5qbLpKm",
      premiumPool: "6iotFayrtj3Uc6gVgyLdrKPgGfHPuMV37houPfi8UNeT",
      spotSerumMarketId: "CKxf35g1CDGSdF6uXFvxAzjEK7iy7G6PZQqcCJFCjqDm",
      depositTokenSymbol: "stSOL",
      depositTokenCoingeckoId: "lido-staked-sol",
      underlyingTokenSymbol: "stSOL",
      underlyingTokenCoingeckoId: "lido-staked-sol",
      voltType: 1,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_income_call_avax: {
      globalId: "mainnet_income_call_avax",
      voltVaultId: "7mzbtntRJL7QPw2rtAcFhqVM7iBvCa6McaatZ5RPPhag",
      extraVaultDataId: "7MDpCGNLKJyUaXhbFe6WqkQHvLKELLwibYj1H5FknkmA",
      vaultAuthority: "5LrULR5w9N1dfnJ9vHnzRkQi9uBL3CkSRWkDGTG6dP1e",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "KgV1GvrHQmRBY8sHQQeUKwTm2r2h8t4C8qt12Cw1HVE",
      depositTokenMint: "KgV1GvrHQmRBY8sHQQeUKwTm2r2h8t4C8qt12Cw1HVE",
      shareTokenMint: "HLfkEc6E2HEcABaWm3QZSfDvswzXjh1onF9xEzUAtWNS",
      shareTokenSymbol: "fcAVAX",
      shareTokenDecimals: 8,
      depositPool: "GjuooH9o3eSSLEwT9SphcNr2H9FpP7Rzd6TuG1zPZrt2",
      premiumPool: "CnBeZfUGxLe8Yeept5rpV6RJjDg7evxMfBJZJmccyZkn",
      spotSerumMarketId: "A5z6Fmd5oHJaehJrDcm7i1kNN8hz1NQLmqpaWoNtFspo",
      depositTokenSymbol: "AVAX",
      depositTokenCoingeckoId: "avalanche-2",
      underlyingTokenSymbol: "AVAX",
      underlyingTokenCoingeckoId: "avalanche-2",
      voltType: 1,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_income_put_luna: {
      globalId: "mainnet_income_put_luna",
      voltVaultId: "3aL9h1PVt2rbUPo11QZpRbpLJhWHrHCpizsirWhMXiXB",
      extraVaultDataId: "7a6MCYkAUb3iQU7hU8v5kfqkBpLGadGyuqUe64x5FMTC",
      vaultAuthority: "5kA7FPiB3t2X5s65dK1AoEu5asDjC5d7f5vaB4iY2yrj",
      quoteMint: "9vMJfxuKxXBoEa7rM12mYLMwTacLMLDJqHozw96WQL8i",
      underlyingMint: "F6v4wfAdJB8D8p77bMXZgYt8TDKsYxLYxH5AFhUkYx9W",
      depositTokenMint: "9vMJfxuKxXBoEa7rM12mYLMwTacLMLDJqHozw96WQL8i",
      shareTokenMint: "74ozhToAS71nDVBtFZMMucdkNB95tV2o5fhtFGQeixwS",
      shareTokenSymbol: "fpLUNA",
      shareTokenDecimals: 6,
      depositPool: "6FVEVQ1FoJD3HbG5s1sHUxNjLD2L53thmrZKvuLmCeVR",
      premiumPool: "4WhTWA9wkL7DBJbPLFsrRv1n5pR1sgYCQaCpdqs3VLsE",
      spotSerumMarketId: "F7kZsKPJQAMT6BgruKfEU2jpu91Jj2iTjNeSpUZstMmd",
      depositTokenSymbol: "UST",
      depositTokenCoingeckoId: "terrausd",
      underlyingTokenSymbol: "LUNA",
      underlyingTokenCoingeckoId: "terra-luna",
      voltType: 2,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_income_put_sol: {
      globalId: "mainnet_income_put_sol",
      voltVaultId: "2evPXRLaTZj92DM93sdryeszwqoC9C6DoWa1TKHn1AzU",
      extraVaultDataId: "GeMAASzD2phRTzvC2HMDtU2zx4typNrYZhJRzKWQih1Y",
      vaultAuthority: "6Nkc8MEiz3WLz1xthYitmSuy3NGwn7782upRHo2iFmXK",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "So11111111111111111111111111111111111111112",
      depositTokenMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      shareTokenMint: "EBPM7fvPN8EuA65Uc7DT9eGyDUZ1sqMLM8Rb8y2YxBYU",
      shareTokenSymbol: "fpSOL",
      shareTokenDecimals: 6,
      depositPool: "3P8gKD391aWea5qyGMeSJJhiXYmLx8n7zY4umh1uYk6j",
      premiumPool: "BxvripadEmktgVyGyf5Nbaxgmpdw3rdkvadRxatFiibj",
      spotSerumMarketId: "C6z5k5fQmdeu7QNnXH1rSYYm22D5dqsMfqEaWgqSUdhM",
      depositTokenSymbol: "USDC",
      depositTokenCoingeckoId: "usd-coin",
      underlyingTokenSymbol: "SOL",
      underlyingTokenCoingeckoId: "solana",
      voltType: 2,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "mainnet_income_put_sol_high",
    },
    mainnet_income_put_sol_high: {
      globalId: "mainnet_income_put_sol_high",
      voltVaultId: "BTuiZkgodmKKJtNDhVQGvAzqW1fdSNWasQADDTTyoAxN",
      extraVaultDataId: "2WizZuJuh1adXkAYMhHPF15zDUY2dBwMeUpSLCZ9MLYK",
      vaultAuthority: "BThMeTgWZBoBbAzp9sK9T7gQzpQDQdRQUVLtVQ3781q1",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "So11111111111111111111111111111111111111112",
      depositTokenMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      shareTokenMint: "G8jsAWUA2KdDn7XmV1sBqUdbEXESaPdjPWDEYCsnkRX2",
      shareTokenSymbol: "fpSOLHigh",
      shareTokenDecimals: 6,
      depositPool: "A9GuE71hkLTgbzM9HEan8uP59bXq96WVANDYEr6Y22Kc",
      premiumPool: "PrVrJeV1KqJGowKwtq8UAzF4McL2P1hW82W2Xk9fQMw",
      spotSerumMarketId: "C6z5k5fQmdeu7QNnXH1rSYYm22D5dqsMfqEaWgqSUdhM",
      depositTokenSymbol: "USDC",
      depositTokenCoingeckoId: "usd-coin",
      underlyingTokenSymbol: "SOL",
      underlyingTokenCoingeckoId: "solana",
      voltType: 2,
      isVoltage: true,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_income_put_mngo: {
      globalId: "mainnet_income_put_mngo",
      voltVaultId: "9SPz2yjNc9V4FmdHrkYF1GfikGbe5rfwg6VPzhQJpPyt",
      extraVaultDataId: "DEg4dUewDBdgGDMGLt1XBsrucsUJSphGf5Rn4ezX3EtC",
      vaultAuthority: "CVrRw6VtxSjokm2tKmaS5RCuoc9EFjN4wEoov6f2PST6",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "MangoCzJ36AjZyKwVj3VnYU4GTonjfVEnJmvvWaxLac",
      depositTokenMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      shareTokenMint: "CxHG1tPkeEHsAVmPF2UrjZK3W719J5DGFgMaLtUkBoeP",
      shareTokenSymbol: "fpMNGO",
      shareTokenDecimals: 6,
      depositPool: "FP7rhnmHexx2Tb4vbt7AX2PjEErSxFgnb8L2NwXwjT1D",
      premiumPool: "Azx3S3FoQGuh1QFfCfAGNVM4XcfzESsT5XN8TmG4Euip",
      spotSerumMarketId: "F7kZsKPJQAMT6BgruKfEU2jpu91Jj2iTjNeSpUZstMmd",
      depositTokenSymbol: "USDC",
      depositTokenCoingeckoId: "usd-coin",
      underlyingTokenSymbol: "MNGO",
      underlyingTokenCoingeckoId: "mango-markets",
      voltType: 2,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_income_put_btc: {
      globalId: "mainnet_income_put_btc",
      voltVaultId: "CzFUVBXaAxWRQ3JeJwsZHqDQUxBbUJLZtdoBQ3KPtsuB",
      extraVaultDataId: "ByJbHcLvbgEAbo9sMetMFeZhHko6SNFR1vPX8FnEvYAu",
      vaultAuthority: "GrB6vbG2WP7eEnbwgxUbBGRMeXYq139jo2o9oW8cNK8f",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E",
      depositTokenMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      shareTokenMint: "THjfJ7GUeW6aMU6dzYYFVs5LnKNvmPzgk2wbh3bWagC",
      shareTokenSymbol: "fpBTC",
      shareTokenDecimals: 6,
      depositPool: "Hzh5dx4K7BDYih4oQvBsgkhwe19TaNnTeyzBDpLJwU8D",
      premiumPool: "H9GxQt8YdrAP8QKCMeqa7kbLC1BNn2716rKD7o4jzMAC",
      spotSerumMarketId: "52Uwi5LjZEox2h9jT3TfQemz15d887FQLbn69RR7hDgF",
      depositTokenSymbol: "USDC",
      depositTokenCoingeckoId: "usd-coin",
      underlyingTokenSymbol: "BTC",
      underlyingTokenCoingeckoId: "bitcoin",
      voltType: 2,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_income_put_tsUSDC: {
      globalId: "mainnet_income_put_tsUSDC",
      voltVaultId: "FFhHmdwHS9myqQPQUMTu8hX56zQETNPC4Bu95ZGb1j5P",
      extraVaultDataId: "2ZQCtSBFAuq6hveRtZ7QiNbKL6v85c7rxEFvs1cdKhSX",
      vaultAuthority: "AQRGh6PU7LzDHvvoPNS7wVVQaCBeftw9kVDAnvuEjbs8",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "So11111111111111111111111111111111111111112",
      depositTokenMint: "Cvvh8nsKZet59nsDDo3orMa3rZnPWQhpgrMCVcRDRgip",
      shareTokenMint: "Fw8mw9zNyfngvBYuS2L6XWfvFE8fExQ3apZVw4Ery5oy",
      shareTokenSymbol: "fptsUSDCSOL",
      shareTokenDecimals: 6,
      depositPool: "HWQn2UdZNzmiPnm8RbuXgeLDnYQGmkw2fJTBD4xso9wD",
      premiumPool: "EmmBNJZzjjuNMASyo5WkZrKLhptDituFtdb3Fruy7bpG",
      spotSerumMarketId: "9ikXcd2mGY2dAtvfEx5vhVSzU28SYv7nMk2cg59bzFeD",
      depositTokenSymbol: "tsUSDC",
      depositTokenCoingeckoId: "usd-coin",
      underlyingTokenSymbol: "SOL",
      underlyingTokenCoingeckoId: "solana",
      voltType: 2,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_income_put_pai: {
      globalId: "mainnet_income_put_pai",
      voltVaultId: "5EU8ykqwFczHa2m8RLFWusRQkBW58kWYCTdCY6mAdMce",
      extraVaultDataId: "9GCaueg1Qv6HixopaGJ2JaSvqnsdfkKexqieyfjCTNfu",
      vaultAuthority: "7Nvs437r3waBgBoFpgsqBjouy5PLP7h2wUFbsF1FD2AK",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "So11111111111111111111111111111111111111112",
      depositTokenMint: "Ea5SjE2Y6yvCeW5dYTn7PYMuW5ikXkvbGdcmSnXeaLjS",
      shareTokenMint: "8R2L3r6N6odiUkztEzhxr9wkFio8UikYWbp36qdZvA9U",
      shareTokenSymbol: "fpPAISOL",
      shareTokenDecimals: 6,
      depositPool: "GqC7LmZCvQ3fXjnuwYAbN57UpkqypKd8xnrJzj23gsHB",
      premiumPool: "GnG4bXr47AHNjubQY39ja2EzPs2vKfR28BdQDsrXuxsL",
      spotSerumMarketId: "Fze6inVkgQtJod6sPfhuTeG1GYAkdRCujjF7FxyYuywk",
      depositTokenSymbol: "PAI",
      depositTokenCoingeckoId: "usd-coin",
      underlyingTokenSymbol: "SOL",
      underlyingTokenCoingeckoId: "solana",
      voltType: 2,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_income_put_uxd: {
      globalId: "mainnet_income_put_uxd",
      voltVaultId: "czeyfQ3tZdfnPwLeRMRCYVHNjhViBR1fUd7giLBNKHA",
      extraVaultDataId: "3jFRqBprZfo8ZmN2kHcCZYv2CQQzkD3oBLjWv6KdQGiV",
      vaultAuthority: "3f6W66hpeW7eLivRgVghFEqgz4NRngWravPh3maDanVb",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "So11111111111111111111111111111111111111112",
      depositTokenMint: "7kbnvuGBxxj8AG9qp8Scn56muWGaRaFqxg1FsRp3PaFT",
      shareTokenMint: "7q415NG2DBRLTcTqMdRLWZ6FTVUzSunjfsjMkT3xneNL",
      shareTokenSymbol: "fpUXDSOL",
      shareTokenDecimals: 6,
      depositPool: "6zbSX5Pf5GjG5wXCavYkAJwiwBHUBFQvbaDLXMDtYVGm",
      premiumPool: "JAGcU3F6CZQRwEZuq8cM6EE9537ezFJffBjdT1Kv6G6A",
      spotSerumMarketId: "Fze6inVkgQtJod6sPfhuTeG1GYAkdRCujjF7FxyYuywk",
      depositTokenSymbol: "UXD",
      depositTokenCoingeckoId: "usd-coin",
      underlyingTokenSymbol: "SOL",
      underlyingTokenCoingeckoId: "solana",
      voltType: 2,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_income_put_eth: {
      globalId: "mainnet_income_put_eth",
      voltVaultId: "2QRujUdQwz5p7XNQWh48KbyZ9AMEbG7WbkuqMMS9KdE5",
      extraVaultDataId: "B6jqwLkq4F5e5YbVvNcEra6T5tQ2D5GSjK7sfkJR9N5S",
      vaultAuthority: "EA29Xf3HGMtYziw7UKZDUKby7gkoCbXwmiNKwc7z54Ax",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "7vfCXTUXx5WJV5JADk17DUJ4ksgau7utNKj4b963voxs",
      depositTokenMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      shareTokenMint: "2uTkms42P62dJ7JRaefc1HFkvyBeMP28J6MPmH1gVHoT",
      shareTokenSymbol: "fpETH",
      shareTokenDecimals: 6,
      depositPool: "G6ZNyhFk1isVfcjgbp1kvWu2e3vcVegMPqyikj4vykU5",
      premiumPool: "AcvBwtSAeUMFiifsUCCq3FWN5qV8mDFZe81He4cgDSkQ",
      spotSerumMarketId: "dg4cpuXc6nWq7L7b7UkKJKFEMGBrUKAjLBGWeLFSnXW",
      depositTokenSymbol: "USDC",
      depositTokenCoingeckoId: "usd-coin",
      underlyingTokenSymbol: "ETH",
      underlyingTokenCoingeckoId: "ethereum",
      voltType: 2,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_income_perp_btc: {
      globalId: "mainnet_income_perp_btc",
      voltVaultId: "JPmAHJBocDi1539s2wfqiGzVTZd4quYJgx5dg6Ysq2k",
      extraVaultDataId: "6b7YMVAkdx1mZqTGA4fpCHt3dRCcVLRd8N5oN8zk2ej2",
      vaultAuthority: "3A9M3rMmAg6SZmNgMuZ1sinriFaTdS9Fmj6c54w1vDG4",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E",
      depositTokenMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      shareTokenMint: "86nx2WyrdC6VuWyfdG1gMLiiBduktBTJgToKZAYwcbct",
      shareTokenSymbol: "fcrabBTC",
      shareTokenDecimals: 6,
      depositPool: "CETrNxZgXDkYXUJ7PyfEmHveJJZGwy6KpY2zqJyZeHDR",
      premiumPool: "11111111111111111111111111111111",
      spotSerumMarketId: "52Uwi5LjZEox2h9jT3TfQemz15d887FQLbn69RR7hDgF",
      depositTokenSymbol: "USDC",
      depositTokenCoingeckoId: "usd-coin",
      underlyingTokenSymbol: "BTC",
      underlyingTokenCoingeckoId: "bitcoin",
      voltType: 3,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_basis_usdc_sol: {
      globalId: "mainnet_basis_usdc_sol",
      voltVaultId: "2yPs4YTdMzuKmYeubfNqH2xxgdEkXMxVcFWnAFbsojS2",
      extraVaultDataId: "FKJEQzbZ42cQNFyTHLCeLWqpLnB4XDP9vbWjaXtZtQuS",
      vaultAuthority: "C2k7bZg3iBaqGM4xXzJiX4VADa2GJ6ZUhdQV76A5dB3Z",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "So11111111111111111111111111111111111111112",
      depositTokenMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      shareTokenMint: "5CNnTMrMmWHnpswWYdFANvP6QCu58azbRG1enAjeWohx",
      shareTokenSymbol: "fbasisSOL",
      shareTokenDecimals: 6,
      depositPool: "D934Ya7TLpMAnfg23q3sTRqLpHEWT42ddf129GKfuSGa",
      premiumPool: "11111111111111111111111111111111",
      spotSerumMarketId: "52Uwi5LjZEox2h9jT3TfQemz15d887FQLbn69RR7hDgF",
      depositTokenSymbol: "USDC",
      depositTokenCoingeckoId: "usd-coin",
      underlyingTokenSymbol: "SOL",
      underlyingTokenCoingeckoId: "solana",
      voltType: 4,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_basis_usdc_btc: {
      globalId: "mainnet_basis_usdc_btc",
      voltVaultId: "5UothAuhBvRgmR3pEEppLUFoCexcuDshgbS1fb1Ad5WR",
      extraVaultDataId: "8s9pomGR273mSmcWFf9nWqh2mzrfEcGNnR79NXWHgbvY",
      vaultAuthority: "Epomtk2m1vF6J74wXxYjRmkZPismCAtriCUxBSR3D1AV",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E",
      depositTokenMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      shareTokenMint: "GjHfbkNE4WbCeiyq8SteXJgtgNH46zWX7zXMKjPbL4Py",
      shareTokenSymbol: "fbasisBTC",
      shareTokenDecimals: 6,
      depositPool: "8PRhuZvt4v5vMDsfQhzvE9uKHhXwHigZF1UTnaHsKhkX",
      premiumPool: "11111111111111111111111111111111",
      spotSerumMarketId: "52Uwi5LjZEox2h9jT3TfQemz15d887FQLbn69RR7hDgF",
      depositTokenSymbol: "USDC",
      depositTokenCoingeckoId: "usd-coin",
      underlyingTokenSymbol: "BTC",
      underlyingTokenCoingeckoId: "bitcoin",
      voltType: 4,
      isVoltage: false,
      isInCircuits: false,
      highVoltage: "",
    },
    mainnet_income_call_sol_step_circuits: {
      globalId: "mainnet_income_call_sol_step_circuits",
      voltVaultId: "vhW9x5PRg6me9HkgGbxo6SVEMpnmnTvA116LY4574Kf",
      extraVaultDataId: "79Q3qFuwpMK4ASMnpBsfXJLXtg5hCa2GMmpKLAXU2poj",
      vaultAuthority: "6g5XdAymR6F8MfsNtg5QiU14cfVLm5npLFmtquJPvqBS",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "So11111111111111111111111111111111111111112",
      depositTokenMint: "So11111111111111111111111111111111111111112",
      shareTokenMint: "FGyxuV712gvc8DtxBrSSFXAU6yfqEzqs2intBYUNobWo",
      shareTokenSymbol: "fcSOL_StepFinanceTreasury",
      shareTokenDecimals: 9,
      depositPool: "BpdNkP1nCqzqTgSvstfRXXM3sQmsVgnNYGoBXRfDpDc1",
      premiumPool: "2FeVRkwmEzVYUHFj3v9P3zy3MjbbcPGcgoiKZx47szp9",
      spotSerumMarketId: "Aj3bg9mGwGyDAkxtWKhHVsJV8X2fhKsZ3tpN1NfYbjWd",
      depositTokenSymbol: "SOL",
      depositTokenCoingeckoId: "solana",
      underlyingTokenSymbol: "SOL",
      underlyingTokenCoingeckoId: "solana",
      voltType: 1,
      isVoltage: false,
      isInCircuits: true,
      highVoltage: "",
    },
    mainnet_income_call_btc_step_circuits: {
      globalId: "mainnet_income_call_btc_step_circuits",
      voltVaultId: "FKBLigfR6Lj8oAjomVxAEzKQcUgwqB6Dwf8chw8CNhJ3",
      extraVaultDataId: "1rVG1VQpohoKzi3r6Whc6ikiqsVEm9X5hFwrJS8JeSs",
      vaultAuthority: "EYwsNSRx49nSitg2e17mr1ArTZ1urFZfPuaC7qLQxoyh",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E",
      depositTokenMint: "9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E",
      shareTokenMint: "5TMXqdmLGfdbmeWDQ1BxZ16xxTcHTA766gnojnS1Cx2g",
      shareTokenSymbol: "fcBTC_StepFinanceTreasury",
      shareTokenDecimals: 6,
      depositPool: "4biyDDBcDhnC4fv2FZAnAAC92wAwYgie7adnEdkcUMWf",
      premiumPool: "Dum8UWN8MpAuVreLa2tj89VdhBCnQD9TnvfJPL6sBgs",
      spotSerumMarketId: "2NksTwSCzD2XERcZN5FHgTWhCVPePWt59mBKmsKGhbhP",
      depositTokenSymbol: "BTC",
      depositTokenCoingeckoId: "bitcoin",
      underlyingTokenSymbol: "BTC",
      underlyingTokenCoingeckoId: "bitcoin",
      voltType: 1,
      isVoltage: false,
      isInCircuits: true,
      highVoltage: "",
    },
    mainnet_income_put_sol_step_circuits: {
      globalId: "mainnet_income_put_sol_step_circuits",
      voltVaultId: "DLZxZ9oStXCN9pKisKveLQemCwTSvjmirQb1zyykMg1H",
      extraVaultDataId: "Hc5KVPshDqkUmFZmeqZg3YjUQmv7KDiPnr1R6WWGm9EB",
      vaultAuthority: "BVrYZ1XpjK85kYKSd2bsQweidBJxHnf8exbpZCNcMdTQ",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "So11111111111111111111111111111111111111112",
      depositTokenMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      shareTokenMint: "Bikt7D3nMQmJSpxX7oczCDKgevrpWk3g4D3VhQZzqAT",
      shareTokenSymbol: "fpSOL_StepFinanceTreasury",
      shareTokenDecimals: 6,
      depositPool: "3C8SvZ9EcYNbEesWh5nF7hEBZgx632ntvkZk5MQ8Hk6h",
      premiumPool: "4ej5fJ2wP2yNbPpWKyjfaaKG3rm4StfPz84XJkTnYtaa",
      spotSerumMarketId: "C6z5k5fQmdeu7QNnXH1rSYYm22D5dqsMfqEaWgqSUdhM",
      depositTokenSymbol: "USDC",
      depositTokenCoingeckoId: "usd-coin",
      underlyingTokenSymbol: "SOL",
      underlyingTokenCoingeckoId: "solana",
      voltType: 2,
      isVoltage: false,
      isInCircuits: true,
      highVoltage: "",
    },
    mainnet_income_call_sol_parrot_circuits: {
      globalId: "mainnet_income_call_sol_parrot_circuits",
      voltVaultId: "D7SgpEHFDZXJtcigj3JSHUm28cTCAArzv5vtGs4GjmmC",
      extraVaultDataId: "ATKtgdvpdm8rXqTqecdnavdMXDFSRgP2zZsdDwZBkXvX",
      vaultAuthority: "2fAqkifQHr5tdu4y6e9g3ZUZnaDhXcCEHPxmoiCzDxN1",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "So11111111111111111111111111111111111111112",
      depositTokenMint: "So11111111111111111111111111111111111111112",
      shareTokenMint: "89JuYPSHEhskTvVf4rkdfmXyr6bdNA6Q21XtjSU7Urdi",
      shareTokenSymbol: "fcSOL_ParrotTreasury",
      shareTokenDecimals: 9,
      depositPool: "DKs5XzPgsXMdY5NhreAQjbka5sn36x9Kgkw5m4j2EJ1H",
      premiumPool: "6C8cYuvsnjKQ5V65WifDJvNbhJ4E66EH8xva5jGyKQLu",
      spotSerumMarketId: "Aj3bg9mGwGyDAkxtWKhHVsJV8X2fhKsZ3tpN1NfYbjWd",
      depositTokenSymbol: "SOL",
      depositTokenCoingeckoId: "solana",
      underlyingTokenSymbol: "SOL",
      underlyingTokenCoingeckoId: "solana",
      voltType: 1,
      isVoltage: false,
      isInCircuits: true,
      highVoltage: "",
    },
    mainnet_income_put_sol_parrot_circuits: {
      globalId: "mainnet_income_put_sol_parrot_circuits",
      voltVaultId: "7ENaTK9GmFadsS7T584D5wDDMsmf4yP8hudAdZR2RBRW",
      extraVaultDataId: "43SR4wqqZGiTB1oA2cLjDsAGEe7HPwoJHzTLbu3iFLTY",
      vaultAuthority: "EevTHu56oXvQSFw8yVFs9spjVCVsxemDLMpvfApW32eD",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "So11111111111111111111111111111111111111112",
      depositTokenMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      shareTokenMint: "J1TX6c1R6WykW2wonvrL6xA2g8vZ2FLDqDDF1mLYrMYK",
      shareTokenSymbol: "fpSOL_ParrotTreasury",
      shareTokenDecimals: 6,
      depositPool: "P7TTBhKxrQg4BS651fB5cLX9Jn2UyL2LxeNayrLEMbX",
      premiumPool: "G1zaeJRjMnehdFXpkoXZWzBPEuunTfREqj9Emb7quKZY",
      spotSerumMarketId: "C6z5k5fQmdeu7QNnXH1rSYYm22D5dqsMfqEaWgqSUdhM",
      depositTokenSymbol: "USDC",
      depositTokenCoingeckoId: "usd-coin",
      underlyingTokenSymbol: "SOL",
      underlyingTokenCoingeckoId: "solana",
      voltType: 2,
      isVoltage: false,
      isInCircuits: true,
      highVoltage: "",
    },
    mainnet_income_put_btc_step_circuits: {
      globalId: "mainnet_income_put_btc_step_circuits",
      voltVaultId: "3ZQniX9gkCmbmRCDtdnMUbWHLQHPXgUsHNmDHNy5H8bH",
      extraVaultDataId: "G4Wnx9JpCCcogYtXXVs8j5ZQGwkseuxKsJ9FhnF7Tjuy",
      vaultAuthority: "8ENPcthqhuWVaTG3eE28zJHxm4BWzyiyCFgqZL44szTY",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "9n4nbM75f5Ui33ZbPYXn59EwSgE8CGsHtAeTH5YFeJ9E",
      depositTokenMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      shareTokenMint: "ET4nQ6we7KDemfzni8dy2EkNCuYo1RryiRPjC6XwnnC3",
      shareTokenSymbol: "fpBTC_StepFinanceTreasury",
      shareTokenDecimals: 6,
      depositPool: "ALo9jmuDsBxjqEpb2rs4UeNDdWK3UPm8TCcTQU4gofkT",
      premiumPool: "2H6ME2cwcY94S43L51UkbPcbePVCvNoLRrBQmFQe1msQ",
      spotSerumMarketId: "C6z5k5fQmdeu7QNnXH1rSYYm22D5dqsMfqEaWgqSUdhM",
      depositTokenSymbol: "USDC",
      depositTokenCoingeckoId: "usd-coin",
      underlyingTokenSymbol: "BTC",
      underlyingTokenCoingeckoId: "bitcoin",
      voltType: 2,
      isVoltage: false,
      isInCircuits: true,
      highVoltage: "",
    },
    mainnet_income_put_sol_uxd_circuits: {
      globalId: "mainnet_income_put_sol_uxd_circuits",
      voltVaultId: "9cHT8d7d35ngj5i8WBZB8ibjnPLnvnym4tp4KoTCQtxw",
      extraVaultDataId: "FEpmsNqZnRMZCjg9kbSa1NtwrGAp6r7gV7M781F9fWND",
      vaultAuthority: "HXNJ9xq648Ju9uJCZjxybBz4VHajMUCGo9hsF3Sb8Yyz",
      quoteMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      underlyingMint: "So11111111111111111111111111111111111111112",
      depositTokenMint: "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v",
      shareTokenMint: "BAyzqZuKUQ4k93Yfm3xp85SkAKtr4xghBsqZLBTZT14z",
      shareTokenSymbol: "fpSOL_UXDTreasury",
      shareTokenDecimals: 6,
      depositPool: "CptnNvSuZwM4jsbApVwdPUyZzzyRzBktA28DRdq5K3zR",
      premiumPool: "2A5tXphoJSsbRhZYPZt4XpfPHfh2oc429RmFfZbrMsbw",
      spotSerumMarketId: "C6z5k5fQmdeu7QNnXH1rSYYm22D5dqsMfqEaWgqSUdhM",
      depositTokenSymbol: "USDC",
      depositTokenCoingeckoId: "usd-coin",
      underlyingTokenSymbol: "SOL",
      underlyingTokenCoingeckoId: "solana",
      voltType: 2,
      isVoltage: false,
      isInCircuits: true,
      highVoltage: "",
    },
  },
};

// To update this, simply copy paste the data from staticData.json

// Assert that each object inside friktionSnapshot.staticInfoByGlobalId is a the corresponding object inside of frozenFriktionSnapshot.staticInfoByGlobalId
// Everything inside friktionSnapshot must be same as in frozenFriktionSnapshot, if exists
// If it doesn't exist, then it is ok
let totalChecks = 0;
// Loop through values of the globalIds array
for (let globalId of Object.keys(staticData.staticInfoByGlobalId)) {
  const frozen: Record<string, JSONValue> | undefined =
    frozenFriktionSnapshot.staticInfoByGlobalId[globalId];
  if (frozen) {
    //@ts-ignore
    const wet: Record<string, JSONValue> =
      staticData.staticInfoByGlobalId[globalId];

    // Check that wet 💦 contains all the properties of frozen
    for (let property in frozen) {
      if (wet[property] !== frozen[property]) {
        console.log("Frozen: ", frozen[property]);
        console.log("Wet: ", wet[property]);
        throw new Error(
          `${globalId} ${property} is different from what we froze inside postprocess-friktionSnapshot.ts`
        );
      }
      totalChecks += 1;
    }
  }
}
const MIN_TOTAL_CHECKS = 735;
console.log(staticData);
console.log();
console.log();
console.log();
console.log();
console.log(
  `${totalChecks} checks performed out of minimum of ${MIN_TOTAL_CHECKS}`
);

fs.writeFileSync(
  "mainnet-tvl-snapshots/staticData.json",
  JSON.stringify(staticData, null, 2)
);

// console.log(staticData);
