import { Card09Props } from "./Card10";
import { GlobalId, STRONG_SUBVOLTS, WEAK_SUBVOLTS } from "./registry10";

/**
 * this is the precursor to the registry.
 *
 * The data will be loaded in use QuarantineProtocol09
 * @deprecated You shouldn't be using this directly. Instaed, use the vfac09
 */
export const DEVNET_PRE_CARD_REGISTRY_VOLT1: Card09Props[] = [
  {
    volt: 3,
    underlyingAssetSymbol: "BTC",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["devnet_income_perp_btc"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 1,
    underlyingAssetSymbol: "SOL",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["devnet_income_call_sol"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
];

export const MAINNET_PRE_CARD_REGISTRY_VOLT1: Card09Props[] = [
  {
    volt: 1,
    underlyingAssetSymbol: "SOL",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["mainnet_income_call_sol"],
    data: null,
    deposits: null,
    highVoltageDef: STRONG_SUBVOLTS["mainnet_income_call_sol_high"],
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 1,
    underlyingAssetSymbol: "SOL",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["mainnet_income_call_sol_high"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 1,
    underlyingAssetSymbol: "BTC",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["mainnet_income_call_btc"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 1,
    underlyingAssetSymbol: "ETH",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["mainnet_income_call_eth"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 1,
    underlyingAssetSymbol: "stSOL",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["mainnet_income_call_stsol"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 1,
    underlyingAssetSymbol: "AVAX",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["mainnet_income_call_avax"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 1,
    underlyingAssetSymbol: "mSOL",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["mainnet_income_call_marinade"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 1,
    underlyingAssetSymbol: "FTT",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["mainnet_income_call_ftt"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 1,
    underlyingAssetSymbol: "SRM",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["mainnet_income_call_srm"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 1,
    underlyingAssetSymbol: "STEP",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["mainnet_income_call_step"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 1,
    underlyingAssetSymbol: "SAMO",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["mainnet_income_call_samo"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 1,
    underlyingAssetSymbol: "NEAR",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["mainnet_income_call_near"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 1,
    underlyingAssetSymbol: "SBR",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["mainnet_income_call_sbr"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 1,
    underlyingAssetSymbol: "MNGO",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["mainnet_income_call_mngo"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 1,
    underlyingAssetSymbol: "RAY",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["mainnet_income_call_ray"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 1,
    underlyingAssetSymbol: "scnSOL",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["mainnet_income_call_socean"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 1,
    underlyingAssetSymbol: "LUNA",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["mainnet_income_call_luna"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 2,
    underlyingAssetSymbol: "SOL",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["mainnet_income_put_sol"],
    data: null,
    deposits: null,
    highVoltageDef: STRONG_SUBVOLTS["mainnet_income_put_sol_high"],
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 2,
    underlyingAssetSymbol: "SOL",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["mainnet_income_put_sol_high"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 2,
    underlyingAssetSymbol: "BTC",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["mainnet_income_put_btc"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 2,
    underlyingAssetSymbol: "ETH",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["mainnet_income_put_eth"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 2,
    underlyingAssetSymbol: "SOL",
    quoteAssetSymbol: "PAI",
    def: STRONG_SUBVOLTS["mainnet_income_put_pai"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 2,
    underlyingAssetSymbol: "SOL",
    quoteAssetSymbol: "tsUSDC",
    def: STRONG_SUBVOLTS["mainnet_income_put_tsUSDC"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 2,
    underlyingAssetSymbol: "MNGO",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["mainnet_income_put_mngo"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 2,
    underlyingAssetSymbol: "SOL",
    quoteAssetSymbol: "UXD",
    def: STRONG_SUBVOLTS["mainnet_income_put_uxd"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 2,
    underlyingAssetSymbol: "LUNA",
    quoteAssetSymbol: "UST",
    def: STRONG_SUBVOLTS["mainnet_income_put_luna"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 3,
    underlyingAssetSymbol: "BTC",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["mainnet_income_perp_btc"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 4,
    underlyingAssetSymbol: "SOL",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["mainnet_basis_usdc_sol"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 4,
    underlyingAssetSymbol: "BTC",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["mainnet_basis_usdc_btc"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
  {
    volt: 5,
    underlyingAssetSymbol: "SOL",
    quoteAssetSymbol: "USDC",
    def: STRONG_SUBVOLTS["mainnet_protection_usdc_sol"],
    data: null,
    deposits: null,
    highVoltageDef: null,
    highVoltageData: null,
    highVoltageDeposits: null,
  },
];

export const CARDS_FOR_NETWORK = {
  devnet: DEVNET_PRE_CARD_REGISTRY_VOLT1,
  "mainnet-beta": MAINNET_PRE_CARD_REGISTRY_VOLT1,
};
/**
 * @deprecated don't use this. only for backward compatibility
 */
export const voltVaultIdToGlobalIdForBackwardCompatibility = (
  voltVaultId: string
): GlobalId | undefined => {
  // STRONG_SUBVOLTS;
  // loop through the STRONG_SUBVOLTS, and find one that has the same voltVaultId
  for (const [, subvolt] of Object.entries(WEAK_SUBVOLTS)) {
    if (subvolt.voltVaultId.toBase58() === voltVaultId) {
      return subvolt.globalId;
    }
  }
};
